### ISSUE TITLE
Append picker popup to `document.body` to avoid being clipped by parent's `overflow: hidden` style.

### ISSUE THREAD

**Issue by fengyuanchen** [gVguy/vue-color-input#1]
Reference Element Plus's [ColorPicker](https://element-plus.org/en-US/component/color-picker.html) compoent.

**Comment by fluentos** [comment]
Are there any plans of doing it? It doesn't play well when used in combination with frameworks like Vuetify.

**Comment by gVguy** [comment]
@fluentos I might add it eventually, maybe even sooner than later. But at this time I can only suggest positioning the element outside of container with `overflow: hidden`, or using a different component which supports the described use case

**Comment by gVguy** [comment]
Implemented in v2

**Comment by ricardasnav** [comment]
> Implemented in v2

Works like a charm! Thank you a lot!
